"""add_fcm_token_and_notification_emails

Revision ID: 7b86edec7cba
Revises: e4fe59ba4d94
Create Date: 2026-07-20 02:56:47.861494
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b86edec7cba'
down_revision: Union[str, None] = 'e4fe59ba4d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fcm_token', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('notification_emails', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_emails')
    op.drop_column('users', 'fcm_token')
    # ### end Alembic commands ###
