"""
112-Day ML Engineer Curriculum — Private Roadmap
THIS FILE IS GITIGNORED. DO NOT PUSH.

Philosophy: Mastery over completion. Every algorithm learned 3 times:
intuition → implement from scratch → use library.
"""
from datetime import date, timedelta

START_DATE = date(2026, 7, 22)  # Day 1

def d(n):
    """Return the calendar date for Day N (1-indexed)."""
    return START_DATE + timedelta(days=n - 1)


# ─────────────────────────────────────────────────────────────────────────────
# FULL 112-DAY CURRICULUM
# ─────────────────────────────────────────────────────────────────────────────

CURRICULUM = [

    # ══════════════════════════════════════════════════════════════════
    # MODULE 1: FOUNDATIONS (Days 1-14)
    # Build the intuition and tools that make every later algorithm feel natural
    # ══════════════════════════════════════════════════════════════════

    {"day": 1, "module": "Foundations", "topic": "Python & NumPy Foundations",
     "video": "NumPy Crash Course", "focus": "Arrays, dtype, shape, ndim, indexing",
     "lecture": "Why NumPy powers ML, memory layout, vectorization overview",
     "math": "Vectors & notation",
     "lab": "Build array utilities without shortcuts — no list comprehension shortcuts",
     "hw": "25 NumPy exercises — create, index, reshape, slice arrays",
     "viva": "Array concepts: contiguous memory, broadcasting rules",
     "interview": "Why NumPy over Python lists? Memory layout? Vectorization?",
     "deliverable": "day01/day01_numpy_basics.ipynb", "revision": "None",
     "mins_video": 60, "mins_lab": 90},

    {"day": 2, "module": "Foundations", "topic": "Advanced NumPy",
     "video": "NumPy Crash Course (Advanced)", "focus": "Slicing, views vs copies, reshaping, broadcasting",
     "lecture": "Broadcasting intuition and performance",
     "math": "Matrix dimensions",
     "lab": "Reimplement broadcasting examples from scratch",
     "hw": "Matrix manipulation tasks — transpose, dot product, element-wise",
     "viva": "Broadcasting questions — when does it apply?",
     "interview": "Explain broadcasting to an interviewer. View vs copy.",
     "deliverable": "day02/day02_numpy_advanced.ipynb", "revision": "Day 1",
     "mins_video": 60, "mins_lab": 90},

    {"day": 3, "module": "Foundations", "topic": "Pandas for ML",
     "video": "Pandas Official Tutorials", "focus": "Series, DataFrame, indexing, filtering",
     "lecture": "Data loading pipeline, tabular representation",
     "math": "Tabular representation",
     "lab": "Titanic dataset exploration — load, inspect, describe",
     "hw": "Clean Titanic dataset — handle missing values, types",
     "viva": "Data preprocessing questions",
     "interview": "Why Pandas before ML? What operations matter most?",
     "deliverable": "day03/day03_pandas.ipynb", "revision": "Days 1-2",
     "mins_video": 60, "mins_lab": 90},

    {"day": 4, "module": "Foundations", "topic": "Data Visualization",
     "video": "Matplotlib + Seaborn Intro", "focus": "Scatter, histogram, boxplot, heatmap",
     "lecture": "How visualization reveals patterns",
     "math": "Correlation intuition",
     "lab": "Plot Titanic insights — survival by class, age, sex",
     "hw": "Visual EDA report — 10+ meaningful plots with observations",
     "viva": "Plot interpretation questions",
     "interview": "Which plot would you choose for X? What does a bimodal histogram suggest?",
     "deliverable": "day04/day04_visualization.ipynb", "revision": "Days 1-3",
     "mins_video": 60, "mins_lab": 90},

    {"day": 5, "module": "Foundations", "topic": "Linear Algebra I — Vectors",
     "video": "3Blue1Brown Essence of Linear Algebra #1-2", "focus": "Vectors, basis, coordinate systems",
     "lecture": "Geometry of vectors, dot product intuition",
     "math": "Dot product derivation, angle formula",
     "lab": "Implement vector operations from scratch — add, scale, dot, norm, angle",
     "hw": "Vector exercises — geometric interpretations",
     "viva": "Dot product viva — what does it measure?",
     "interview": "Why is dot product important in ML? Cosine similarity?",
     "deliverable": "day05/day05_vectors.ipynb", "revision": "Days 1-4",
     "mins_video": 45, "mins_lab": 90},

    {"day": 6, "module": "Foundations", "topic": "Linear Algebra II — Matrices",
     "video": "3Blue1Brown #3-4", "focus": "Matrix multiplication, linear transformations",
     "lecture": "Matrix intuition — change of basis, transformations",
     "math": "Matrix multiplication as composition of transformations",
     "lab": "Matrix multiplication from scratch — no numpy.matmul",
     "hw": "Solve transformation problems — rotation, shear, scale matrices",
     "viva": "Matrix questions — rank, determinant, inverse",
     "interview": "Matrix vs vector interview. When is matrix multiplication not commutative?",
     "deliverable": "day06/day06_matrices.ipynb", "revision": "Day 5",
     "mins_video": 45, "mins_lab": 90},

    {"day": 7, "module": "Foundations", "topic": "Statistics I",
     "video": "StatQuest Statistics Playlist (Mean, Variance, Normal Dist)", "focus": "Mean, median, mode, variance, standard deviation",
     "lecture": "Why statistics drives ML",
     "math": "Variance derivation — population vs sample",
     "lab": "Implement statistics library from scratch — no numpy.std, numpy.mean",
     "hw": "Statistical exercises on Titanic dataset",
     "viva": "Bias vs variance. Why standard deviation?",
     "interview": "Why standard deviation? When to use median over mean?",
     "deliverable": "day07/day07_statistics.ipynb", "revision": "Days 1-6",
     "mins_video": 60, "mins_lab": 90},

    # WEEK 1 MINI PROJECT (Day 8 = Saturday)
    {"day": 8, "module": "Foundations", "topic": "WEEK 1 PROJECT: Titanic EDA",
     "video": "None (project day)", "focus": "Full EDA pipeline",
     "lecture": "None",
     "math": "Statistical summary",
     "lab": "Load → Clean → Analyze → Visualize → Conclude → Push to GitHub",
     "hw": "Write 500-word summary of findings",
     "viva": "Present your EDA: what story does the data tell?",
     "interview": "Walk me through your EDA process",
     "deliverable": "projects/week01_titanic_eda/", "revision": "Days 1-7",
     "mins_video": 0, "mins_lab": 180, "is_project_day": True},

    {"day": 9, "module": "Foundations", "topic": "Probability & Bayes",
     "video": "StatQuest Probability Playlist", "focus": "Conditional probability, Bayes theorem",
     "lecture": "Thinking probabilistically",
     "math": "Bayes theorem derivation — P(A|B) = P(B|A)P(A)/P(B)",
     "lab": "Bayesian probability calculator from scratch",
     "hw": "Probability worksheet",
     "viva": "Bayes questions — spam filter example",
     "interview": "Real-world probability — how would you detect email spam using Bayes?",
     "deliverable": "day09/day09_probability.ipynb", "revision": "Day 7",
     "mins_video": 60, "mins_lab": 90},

    {"day": 10, "module": "Foundations", "topic": "Calculus for ML",
     "video": "Calculus Essentials (Khan Academy or MIT OCW)", "focus": "Derivatives, slopes, gradients",
     "lecture": "Why derivatives matter in ML",
     "math": "Chain rule intuition and derivation",
     "lab": "Numerical differentiation — implement forward/central difference",
     "hw": "Derivative worksheet — compute derivatives of ML loss functions",
     "viva": "Gradient questions — what is a gradient?",
     "interview": "Why derivatives in ML? Chain rule in backprop?",
     "deliverable": "day10/day10_calculus.ipynb", "revision": "Days 5-9",
     "mins_video": 60, "mins_lab": 90},

    {"day": 11, "module": "Foundations", "topic": "Optimization & Gradient Descent",
     "video": "Gradient Descent Intuition (StatQuest + 3B1B Neural Networks Ch1)", "focus": "Cost surfaces, minima, learning rate",
     "lecture": "Optimization before ML — why we minimize",
     "math": "Gradient concept — partial derivatives",
     "lab": "Visualize optimization — plot cost surface, animate gradient descent",
     "hw": "Learning-rate experiments — too high, too low, just right",
     "viva": "Local minima, saddle points, learning rate scheduling",
     "interview": "Why optimization? How does learning rate affect convergence?",
     "deliverable": "day11/day11_optimization.ipynb", "revision": "Day 10",
     "mins_video": 60, "mins_lab": 90},

    {"day": 12, "module": "Foundations", "topic": "ML Introduction",
     "video": "Stanford CS229 Lecture 1", "focus": "What is ML? Supervised vs Unsupervised, ML workflow",
     "lecture": "ML landscape and workflow",
     "math": "Feature vector notation — x ∈ R^n",
     "lab": "First ML pipeline — load data, split, train, predict, evaluate",
     "hw": "Read about 5 real-world ML datasets",
     "viva": "ML basics — types, applications",
     "interview": "Types of ML. How would you approach a new ML problem?",
     "deliverable": "day12/day12_intro_ml.ipynb", "revision": "Days 1-11",
     "mins_video": 75, "mins_lab": 60},

    {"day": 13, "module": "Foundations", "topic": "Linear Regression Intuition",
     "video": "Stanford CS229 Lecture 1 (continued)", "focus": "Hypothesis function, training examples, parameters",
     "lecture": "Why regression works — geometry of least squares",
     "math": "Linear equation: h(x) = θ₀ + θ₁x",
     "lab": "Predict house prices manually — no sklearn",
     "hw": "Small regression worksheet",
     "viva": "Regression intuition — what does the slope represent?",
     "interview": "Why linear regression? What are its assumptions?",
     "deliverable": "day13/day13_regression_intro.ipynb", "revision": "Day 12",
     "mins_video": 60, "mins_lab": 90},

    {"day": 14, "module": "Foundations", "topic": "Cost Function & Gradient Descent from Scratch",
     "video": "Stanford CS229 Lecture 1", "focus": "MSE, Gradient Descent algorithm, convergence",
     "lecture": "Error surface intuition, optimization geometry",
     "math": "MSE derivation, gradient of MSE, update rule",
     "lab": "Implement full Linear Regression from scratch — data loader, MSE, GD, predict, plot loss",
     "hw": "California Housing regression — compare with sklearn",
     "viva": "20-question viva on everything learned Days 1-14",
     "interview": "Explain Gradient Descent on a whiteboard. Why MSE over MAE?",
     "deliverable": "day14/day14_gradient_descent.ipynb", "revision": "Days 1-13",
     "mins_video": 60, "mins_lab": 120},

    # WEEK 2 MINI PROJECT (Day 15 = Saturday-ish)
    {"day": 15, "module": "Foundations", "topic": "WEEK 2 PROJECT: Linear Regression from Scratch",
     "video": "None (project day)", "focus": "Complete implementation",
     "lecture": "None",
     "math": "Full derivation review",
     "lab": "Build complete LinearRegression class: fit(), predict(), score(), plot_loss(). Compare with sklearn.",
     "hw": "Write README explaining every design decision",
     "viva": "Code review — walk through every line",
     "interview": "Implement Linear Regression from scratch (whiteboard)",
     "deliverable": "projects/week02_linear_regression/", "revision": "Days 1-14",
     "mins_video": 0, "mins_lab": 240, "is_project_day": True},

    # ══════════════════════════════════════════════════════════════════
    # MODULE 2: CLASSICAL ML (Days 16-49)
    # ══════════════════════════════════════════════════════════════════

    {"day": 16, "module": "Classical ML", "topic": "Logistic Regression Theory",
     "video": "Stanford CS229 Lecture 3", "focus": "Classification, sigmoid, decision boundary",
     "lecture": "From regression to classification",
     "math": "Sigmoid function, logistic model, log-odds",
     "lab": "Plot sigmoid, visualize decision boundary in 2D",
     "hw": "Derive the log-likelihood for logistic regression",
     "viva": "Why sigmoid? What is a decision boundary?",
     "interview": "Linear vs Logistic Regression. When would you use logistic?",
     "deliverable": "day16/day16_logistic_theory.ipynb", "revision": "Day 14",
     "mins_video": 75, "mins_lab": 90},

    {"day": 17, "module": "Classical ML", "topic": "Logistic Regression Math",
     "video": "Stanford CS229 Lecture 3 (continued)", "focus": "Log-loss, MLE derivation",
     "lecture": "Maximum Likelihood Estimation",
     "math": "Cross-entropy loss derivation from MLE",
     "lab": "Implement log-loss from scratch, verify against sklearn",
     "hw": "Manually compute log-loss on toy dataset",
     "viva": "Why cross-entropy for classification? KL-divergence connection?",
     "interview": "Why cross-entropy instead of MSE for classification?",
     "deliverable": "day17/day17_logloss_mle.ipynb", "revision": "Day 16",
     "mins_video": 60, "mins_lab": 90},

    {"day": 18, "module": "Classical ML", "topic": "Logistic Regression from Scratch",
     "video": "None (implementation day)", "focus": "Full implementation",
     "lecture": "None",
     "math": "Gradient of log-loss",
     "lab": "Build LogisticRegression class — fit with gradient descent, predict, accuracy, plot boundary",
     "hw": "Breast cancer dataset classification",
     "viva": "Walk through your gradient update step",
     "interview": "Implement logistic regression from scratch (Python)",
     "deliverable": "day18/day18_logistic_scratch.ipynb", "revision": "Days 16-17",
     "mins_video": 0, "mins_lab": 150},

    {"day": 19, "module": "Classical ML", "topic": "Classification Metrics",
     "video": "StatQuest Confusion Matrix + ROC/AUC", "focus": "Precision, recall, F1, ROC-AUC",
     "lecture": "Choosing the right metric",
     "math": "Precision = TP/(TP+FP), Recall = TP/(TP+FN), F1 = harmonic mean",
     "lab": "Implement all metrics from confusion matrix — no sklearn.metrics",
     "hw": "Imbalanced dataset exercise — when does accuracy fail?",
     "viva": "Precision vs recall tradeoff. When to optimize for each?",
     "interview": "What metric would you use for fraud detection? Explain ROC-AUC.",
     "deliverable": "day19/day19_metrics.ipynb", "revision": "Day 18",
     "mins_video": 60, "mins_lab": 90},

    {"day": 20, "module": "Classical ML", "topic": "Regularization",
     "video": "StatQuest Ridge, Lasso", "focus": "L1 vs L2, when to use each",
     "lecture": "Overfitting, underfitting, regularization",
     "math": "Ridge: MSE + λ||θ||², Lasso: MSE + λ||θ||₁",
     "lab": "Add L2 regularization to your LinearRegression — compare coefficients",
     "hw": "Experiment with λ values, plot coefficient shrinkage",
     "viva": "Why does L1 produce sparsity? L2 doesn't?",
     "interview": "Explain regularization. How would you choose λ?",
     "deliverable": "day20/day20_regularization.ipynb", "revision": "Days 14-19",
     "mins_video": 60, "mins_lab": 90},

    {"day": 21, "module": "Classical ML", "topic": "WEEK 3 PROJECT: House Price Prediction",
     "video": "None (project day)", "focus": "Full ML pipeline",
     "lecture": "None",
     "math": "None",
     "lab": "Kaggle House Prices — EDA → Feature Engineering → Linear/Ridge Regression → Evaluate → Deploy simple Flask API",
     "hw": "Write project report: problem, approach, results, learnings",
     "viva": "Project review: choices made, what would you improve?",
     "interview": "Walk me through your end-to-end ML project",
     "deliverable": "projects/week03_house_prices/", "revision": "Days 1-20",
     "mins_video": 0, "mins_lab": 300, "is_project_day": True},

    {"day": 22, "module": "Classical ML", "topic": "Decision Trees Theory",
     "video": "StatQuest Decision Trees", "focus": "Recursive partitioning, information gain",
     "lecture": "How trees make decisions",
     "math": "Entropy, Gini impurity, information gain",
     "lab": "Visualize a decision tree on toy dataset",
     "hw": "Calculate information gain by hand on a small example",
     "viva": "When does a decision tree stop splitting?",
     "interview": "Decision Tree vs Logistic Regression — when to choose which?",
     "deliverable": "day22/day22_trees_theory.ipynb", "revision": "Days 16-20",
     "mins_video": 60, "mins_lab": 90},

    {"day": 23, "module": "Classical ML", "topic": "Decision Trees from Scratch",
     "video": "None (implementation day)", "focus": "Full implementation",
     "lecture": "None",
     "math": "Information gain formula",
     "lab": "Build DecisionTreeClassifier from scratch — Node class, fit, predict",
     "hw": "Test on Iris and Breast Cancer datasets",
     "viva": "Walk through your split function",
     "interview": "Implement a decision tree in Python",
     "deliverable": "day23/day23_tree_scratch.ipynb", "revision": "Day 22",
     "mins_video": 0, "mins_lab": 180},

    {"day": 24, "module": "Classical ML", "topic": "Random Forests & Ensemble Methods",
     "video": "StatQuest Random Forests + Bagging", "focus": "Bagging, feature randomness, OOB error",
     "lecture": "Why ensembles beat single models",
     "math": "Variance reduction through averaging",
     "lab": "Build RandomForest using your DecisionTree — add bagging + feature sampling",
     "hw": "Compare single tree vs forest on noisy data",
     "viva": "Why does bagging reduce variance?",
     "interview": "Random Forest vs Decision Tree. When does RF fail?",
     "deliverable": "day24/day24_random_forest.ipynb", "revision": "Day 23",
     "mins_video": 60, "mins_lab": 120},

    {"day": 25, "module": "Classical ML", "topic": "Gradient Boosting & XGBoost",
     "video": "StatQuest Gradient Boosting", "focus": "Sequential ensemble, residual fitting",
     "lecture": "Boosting intuition vs bagging",
     "math": "Additive model, stage-wise optimization",
     "lab": "XGBoost on Titanic — tune n_estimators, learning_rate, max_depth",
     "hw": "Compare RF vs XGBoost on same dataset",
     "viva": "Boosting vs Bagging — when to use each?",
     "interview": "How does XGBoost differ from Random Forest? What is regularization in XGBoost?",
     "deliverable": "day25/day25_boosting.ipynb", "revision": "Day 24",
     "mins_video": 60, "mins_lab": 90},

    {"day": 26, "module": "Classical ML", "topic": "SVM Theory",
     "video": "Stanford CS229 Lecture 6-7", "focus": "Maximum margin classifier, support vectors",
     "lecture": "Geometric intuition of SVMs",
     "math": "Hard-margin SVM: maximize 2/||w||, soft-margin: add slack variables",
     "lab": "Visualize SVM decision boundary + margins in 2D",
     "hw": "Derive the dual form of the SVM objective",
     "viva": "What is a support vector? What is the kernel trick?",
     "interview": "SVM vs Logistic Regression. When would you use SVM?",
     "deliverable": "day26/day26_svm.ipynb", "revision": "Days 22-25",
     "mins_video": 75, "mins_lab": 90},

    {"day": 27, "module": "Classical ML", "topic": "Naive Bayes Classifier",
     "video": "StatQuest Naive Bayes", "focus": "Conditional independence assumption",
     "lecture": "Why naive independence works in practice",
     "math": "P(y|x) ∝ P(y) ∏ P(xᵢ|y)",
     "lab": "Build GaussianNaiveBayes from scratch",
     "hw": "Text classification: classify news articles",
     "viva": "When does Naive Bayes fail? When does it excel?",
     "interview": "NB vs Logistic Regression. How does NB scale with features?",
     "deliverable": "day27/day27_naive_bayes.ipynb", "revision": "Day 9",
     "mins_video": 45, "mins_lab": 90},

    {"day": 28, "module": "Classical ML", "topic": "K-Nearest Neighbors",
     "video": "StatQuest KNN", "focus": "Distance metrics, k selection",
     "lecture": "Lazy learning intuition",
     "math": "Euclidean, Manhattan, Cosine distance",
     "lab": "Build KNN classifier from scratch — find k nearest, vote",
     "hw": "Plot accuracy vs k on Iris dataset",
     "viva": "Computational cost of KNN. When does it fail?",
     "interview": "KNN: how does k affect bias-variance? Curse of dimensionality?",
     "deliverable": "day28/day28_knn.ipynb", "revision": "Days 22-27",
     "mins_video": 45, "mins_lab": 90},

    {"day": 29, "module": "Classical ML", "topic": "WEEK 4 PROJECT: Customer Churn Prediction",
     "video": "None (project day)", "focus": "Full classification project",
     "lecture": "None",
     "math": "None",
     "lab": "Telco churn dataset — EDA + LogReg + Tree + RF + XGBoost + compare → best model → report",
     "hw": "Business presentation: which model, why, what's the business impact?",
     "viva": "Why did you choose this evaluation metric?",
     "interview": "Walk me through your model selection process",
     "deliverable": "projects/week04_churn/", "revision": "Days 16-28",
     "mins_video": 0, "mins_lab": 300, "is_project_day": True},

    {"day": 30, "module": "Classical ML", "topic": "Clustering — K-Means",
     "video": "StatQuest K-Means Clustering", "focus": "Unsupervised learning, centroid update",
     "lecture": "When we don't have labels",
     "math": "K-Means objective: minimize within-cluster variance",
     "lab": "Build K-Means from scratch — E-step, M-step, convergence",
     "hw": "Customer segmentation on retail dataset",
     "viva": "K-Means limitations — why does initialization matter?",
     "interview": "How do you choose K? What if clusters are non-spherical?",
     "deliverable": "day30/day30_kmeans.ipynb", "revision": "Days 1-29",
     "mins_video": 45, "mins_lab": 90},

    {"day": 31, "module": "Classical ML", "topic": "Dimensionality Reduction — PCA",
     "video": "StatQuest PCA + 3Blue1Brown (eigenvectors)", "focus": "Eigenvalues, eigenvectors, variance explained",
     "lecture": "Why we reduce dimensions",
     "math": "Covariance matrix, eigendecomposition",
     "lab": "Implement PCA from scratch — covariance → eigenvectors → project",
     "hw": "Visualize MNIST digits in 2D using PCA",
     "viva": "How many components to keep? Explained variance ratio?",
     "interview": "PCA vs Feature Selection. When to use PCA?",
     "deliverable": "day31/day31_pca.ipynb", "revision": "Days 5-6",
     "mins_video": 60, "mins_lab": 120},

    {"day": 32, "module": "Classical ML", "topic": "Feature Engineering",
     "video": "Kaggle Feature Engineering Course (free)", "focus": "Encoding, scaling, interactions",
     "lecture": "Features determine model performance",
     "math": "Label encoding vs one-hot vs ordinal",
     "lab": "Feature engineering pipeline on Titanic — 10 new features",
     "hw": "Feature importance analysis using RF",
     "viva": "Why scale features? When not to scale?",
     "interview": "How do you handle categorical variables? High cardinality?",
     "deliverable": "day32/day32_feature_eng.ipynb", "revision": "Days 3-4",
     "mins_video": 60, "mins_lab": 90},

    {"day": 33, "module": "Classical ML", "topic": "Cross-Validation & Model Selection",
     "video": "StatQuest Cross-Validation", "focus": "K-fold, stratified, nested CV",
     "lecture": "Why simple train/test split is not enough",
     "math": "Bias-variance tradeoff, test set contamination",
     "lab": "Implement K-Fold CV from scratch, compare with sklearn",
     "hw": "Model selection experiment on churn dataset",
     "viva": "Why stratified K-fold for imbalanced data?",
     "interview": "What is data leakage? How does CV prevent it?",
     "deliverable": "day33/day33_cross_validation.ipynb", "revision": "Days 14-19",
     "mins_video": 45, "mins_lab": 90},

    {"day": 34, "module": "Classical ML", "topic": "Hyperparameter Tuning",
     "video": "Kaggle Hyperparameter Optimization", "focus": "Grid search, random search, Bayesian optimization",
     "lecture": "Systematic vs manual tuning",
     "math": "None",
     "lab": "GridSearchCV + RandomizedSearchCV on RF + XGBoost",
     "hw": "Tune your best churn model — target 5% AUC improvement",
     "viva": "When does grid search fail? Why random search often wins?",
     "interview": "How do you tune hyperparameters in production?",
     "deliverable": "day34/day34_tuning.ipynb", "revision": "Days 24-25",
     "mins_video": 45, "mins_lab": 90},

    {"day": 35, "module": "Classical ML", "topic": "End-to-End ML Pipeline",
     "video": "None (synthesis day)", "focus": "From raw data to deployed model",
     "lecture": "Production ML workflow overview",
     "math": "None",
     "lab": "Build Pipeline object: Imputer + Scaler + Encoder + Model. Save with joblib.",
     "hw": "Write a 500-word explainer: ML engineering vs ML research",
     "viva": "Walk me through deploying an ML model",
     "interview": "What happens after you train a model?",
     "deliverable": "day35/day35_pipeline.ipynb", "revision": "Days 20-34",
     "mins_video": 0, "mins_lab": 120},

    {"day": 36, "module": "Classical ML", "topic": "WEEK 5/6 PROJECT: Fraud Detection System",
     "video": "None (project day)", "focus": "Imbalanced classification, production pipeline",
     "lecture": "None",
     "math": "SMOTE, class_weight",
     "lab": "Kaggle IEEE Fraud or PaySim — full pipeline: EDA, feature eng, model, evaluate, explain, API",
     "hw": "Business deck: model performance + business impact",
     "viva": "Walk through your imbalanced data strategy",
     "interview": "How would you build a fraud detection system at scale?",
     "deliverable": "projects/week05_fraud_detection/", "revision": "Days 16-35",
     "mins_video": 0, "mins_lab": 360, "is_project_day": True},

    # REVISION WEEK (Days 37-42)
    {"day": 37, "module": "Classical ML", "topic": "Revision: Regression algorithms",
     "video": "None (revision day)", "focus": "Linear Reg, Ridge, Lasso, Polynomial",
     "lecture": "None", "math": "Re-derive cost functions",
     "lab": "Recode Linear Regression + Ridge without notes",
     "hw": "5 interview questions on regression",
     "viva": "Surprise viva on regression",
     "interview": "Full regression interview prep",
     "deliverable": "revision/regression_revision.ipynb", "revision": "Days 12-20",
     "mins_video": 0, "mins_lab": 120, "is_revision_day": True},

    {"day": 38, "module": "Classical ML", "topic": "Revision: Classification algorithms",
     "video": "None (revision day)", "focus": "LogReg, Trees, RF, XGBoost, SVM, NB, KNN",
     "lecture": "None", "math": "Re-derive cross-entropy",
     "lab": "Recode LogisticRegression without notes",
     "hw": "5 interview questions on classification",
     "viva": "Surprise viva on classification",
     "interview": "Full classification interview prep",
     "deliverable": "revision/classification_revision.ipynb", "revision": "Days 16-29",
     "mins_video": 0, "mins_lab": 120, "is_revision_day": True},

    {"day": 39, "module": "Classical ML", "topic": "Revision: Unsupervised + Feature Engineering",
     "video": "None (revision day)", "focus": "K-Means, PCA, feature engineering",
     "lecture": "None", "math": "Re-derive PCA from covariance matrix",
     "lab": "Recode K-Means without notes",
     "hw": "5 interview questions on unsupervised learning",
     "viva": "Surprise viva on PCA",
     "interview": "Unsupervised learning interview prep",
     "deliverable": "revision/unsupervised_revision.ipynb", "revision": "Days 30-35",
     "mins_video": 0, "mins_lab": 120, "is_revision_day": True},

    # ══════════════════════════════════════════════════════════════════
    # MODULE 3: DEEP LEARNING (Days 40-77)
    # ══════════════════════════════════════════════════════════════════

    {"day": 40, "module": "Deep Learning", "topic": "Neural Networks Intuition",
     "video": "3Blue1Brown Neural Networks Ch 1-2 + Karpathy intro", "focus": "Neurons, layers, activation functions",
     "lecture": "From linear models to deep networks",
     "math": "Forward pass: z = Wx + b, a = σ(z)",
     "lab": "Build a 2-layer neural net manually on XOR problem",
     "hw": "Draw the computation graph for a 3-layer network",
     "viva": "What is an activation function? Why not linear?",
     "interview": "What is a neural network? Why deep?",
     "deliverable": "day40/day40_nn_intuition.ipynb", "revision": "Days 5-6, 10-11",
     "mins_video": 60, "mins_lab": 90},

    {"day": 41, "module": "Deep Learning", "topic": "Backpropagation Intuition",
     "video": "3Blue1Brown Neural Networks Ch 3-4", "focus": "Gradient flow, chain rule",
     "lecture": "Backprop as credit assignment",
     "math": "Chain rule applied to neural networks",
     "lab": "Manually compute gradients for 2-layer network step by step",
     "hw": "Derive backprop for one layer",
     "viva": "Vanishing gradient problem — why does it happen?",
     "interview": "Explain backpropagation. How does it relate to chain rule?",
     "deliverable": "day41/day41_backprop.ipynb", "revision": "Day 40",
     "mins_video": 60, "mins_lab": 90},

    {"day": 42, "module": "Deep Learning", "topic": "Build micrograd (Karpathy Episode 1)",
     "video": "Karpathy Zero to Hero: Building micrograd", "focus": "Autograd from scratch",
     "lecture": "Computational graphs and automatic differentiation",
     "math": "Value class, gradient accumulation",
     "lab": "Code along with Karpathy — build Value class with backward()",
     "hw": "Add new operations: tanh, relu, power",
     "viva": "How does autograd know which operations to differentiate?",
     "interview": "How does PyTorch/TensorFlow compute gradients automatically?",
     "deliverable": "day42/day42_micrograd.py", "revision": "Day 41",
     "mins_video": 120, "mins_lab": 90},

    {"day": 43, "module": "Deep Learning", "topic": "Build Neural Network from Scratch (NumPy)",
     "video": "None (implementation day)", "focus": "Full forward + backward pass",
     "lecture": "None",
     "math": "Matrix calculus — dL/dW, dL/db",
     "lab": "Build NeuralNetwork class in NumPy — layers, activations, forward, backward, update",
     "hw": "Train on MNIST, achieve >95% accuracy",
     "viva": "Walk through your backward pass implementation",
     "interview": "Implement a neural network in NumPy",
     "deliverable": "day43/day43_nn_numpy.ipynb", "revision": "Days 40-42",
     "mins_video": 0, "mins_lab": 240},

    {"day": 44, "module": "Deep Learning", "topic": "PyTorch Basics",
     "video": "Official PyTorch Tutorial", "focus": "Tensors, autograd, nn.Module",
     "lecture": "PyTorch design philosophy",
     "math": "Tensor operations — same as NumPy but with gradients",
     "lab": "Reimplement your NumPy NN in PyTorch — same problem, compare code",
     "hw": "PyTorch exercises: tensors, gradient computation, custom loss",
     "viva": "torch.Tensor vs numpy.ndarray — key differences?",
     "interview": "Why PyTorch? Eager vs static computation graphs?",
     "deliverable": "day44/day44_pytorch_basics.ipynb", "revision": "Day 43",
     "mins_video": 90, "mins_lab": 90},

    {"day": 45, "module": "Deep Learning", "topic": "Training Deep Networks",
     "video": "MIT Deep Learning Lecture on Optimization", "focus": "Optimizers, batch norm, dropout",
     "lecture": "Why Adam outperforms SGD",
     "math": "Adam update rule: first and second moment estimates",
     "lab": "Experiment: SGD vs Momentum vs Adam on MNIST — compare convergence plots",
     "hw": "Add dropout to your PyTorch model, analyze effect on overfitting",
     "viva": "What is batch normalization? Where to place it?",
     "interview": "Optimizer choices. When would you use SGD over Adam?",
     "deliverable": "day45/day45_training.ipynb", "revision": "Day 44",
     "mins_video": 60, "mins_lab": 90},

    {"day": 46, "module": "Deep Learning", "topic": "WEEK 7 PROJECT: Neural Net from Scratch vs PyTorch",
     "video": "None (project day)", "focus": "Full comparison",
     "lecture": "None",
     "math": "None",
     "lab": "Same problem (MNIST or custom dataset) — NumPy NN vs PyTorch NN. Same architecture, compare accuracy + training time + code complexity.",
     "hw": "1-page analysis: what PyTorch gives you for free",
     "viva": "Why use frameworks at all?",
     "interview": "Tradeoffs of custom vs framework implementation",
     "deliverable": "projects/week07_nn_comparison/", "revision": "Days 40-45",
     "mins_video": 0, "mins_lab": 300, "is_project_day": True},

    {"day": 47, "module": "Deep Learning", "topic": "Convolutional Neural Networks Theory",
     "video": "MIT Deep Learning CNNs lecture", "focus": "Convolution operation, pooling, receptive field",
     "lecture": "Why convolutions for images",
     "math": "Cross-correlation formula, parameter sharing",
     "lab": "Visualize convolution kernels — edge detection, blur, sharpen",
     "hw": "Manually compute a convolution on a 5x5 image",
     "viva": "Why parameter sharing in CNNs? Pooling purpose?",
     "interview": "CNN architecture. Why convolutions instead of fully connected?",
     "deliverable": "day47/day47_cnn_theory.ipynb", "revision": "Days 40-45",
     "mins_video": 75, "mins_lab": 90},

    {"day": 48, "module": "Deep Learning", "topic": "CNN Implementation in PyTorch",
     "video": "None (implementation day)", "focus": "Build LeNet/VGG-style CNN",
     "lecture": "None",
     "math": "Output size formula: ⌊(N-F+2P)/S⌋ + 1",
     "lab": "Build CNN for CIFAR-10 — conv layers, batchnorm, dropout, train, evaluate",
     "hw": "Achieve >80% on CIFAR-10 test set",
     "viva": "How does depth affect receptive field?",
     "interview": "Implement a CNN in PyTorch for image classification",
     "deliverable": "day48/day48_cnn_pytorch.ipynb", "revision": "Day 47",
     "mins_video": 0, "mins_lab": 180},

    {"day": 49, "module": "Deep Learning", "topic": "Transfer Learning",
     "video": "PyTorch Transfer Learning Tutorial", "focus": "Feature extraction, fine-tuning",
     "lecture": "Why pre-trained models are so powerful",
     "math": "None",
     "lab": "Fine-tune ResNet-18 on a custom 5-class dataset",
     "hw": "Compare: train from scratch vs transfer learning — accuracy + time",
     "viva": "When to fine-tune all layers vs just the head?",
     "interview": "How would you use transfer learning for a new task with limited data?",
     "deliverable": "day49/day49_transfer_learning.ipynb", "revision": "Day 48",
     "mins_video": 60, "mins_lab": 120},

    {"day": 50, "module": "Deep Learning", "topic": "Recurrent Networks Theory",
     "video": "MIT Deep Learning RNNs lecture", "focus": "Sequence modeling, hidden state",
     "lecture": "Processing sequences with memory",
     "math": "h_t = tanh(W_h * h_{t-1} + W_x * x_t + b)",
     "lab": "Build a character-level RNN from scratch for name generation",
     "hw": "Vanishing gradient in RNNs — demonstrate with gradients",
     "viva": "Why do RNNs have vanishing gradients?",
     "interview": "RNN vs LSTM. When would you use each?",
     "deliverable": "day50/day50_rnn.ipynb", "revision": "Days 40-45",
     "mins_video": 75, "mins_lab": 120},

    {"day": 51, "module": "Deep Learning", "topic": "LSTM & GRU",
     "video": "StatQuest LSTM", "focus": "Gates, cell state, forget gate",
     "lecture": "How gates solve vanishing gradient",
     "math": "LSTM gate equations",
     "lab": "Build LSTM for time-series forecasting on stock data",
     "hw": "Compare RNN vs LSTM on long sequences",
     "viva": "What does the forget gate do? Cell state vs hidden state?",
     "interview": "When would you choose LSTM over Transformer?",
     "deliverable": "day51/day51_lstm.ipynb", "revision": "Day 50",
     "mins_video": 60, "mins_lab": 120},

    {"day": 52, "module": "Deep Learning", "topic": "WEEK 8 PROJECT: Image Classification CNN",
     "video": "None (project day)", "focus": "Production-quality CNN",
     "lecture": "None",
     "math": "None",
     "lab": "Choose a real dataset (CIFAR-10 or custom) — full pipeline: augmentation + CNN + training loop + evaluation + save model",
     "hw": "Deploy as a simple web app",
     "viva": "Walk through every architecture decision",
     "interview": "How would you deploy an image classifier?",
     "deliverable": "projects/week08_image_classifier/", "revision": "Days 47-51",
     "mins_video": 0, "mins_lab": 360, "is_project_day": True},

    {"day": 53, "module": "Deep Learning", "topic": "Attention Mechanism",
     "video": "3Blue1Brown Attention + Karpathy GPT intro", "focus": "Query, Key, Value, scaled dot product",
     "lecture": "Why attention replaced RNNs",
     "math": "Attention(Q,K,V) = softmax(QK^T/√d)V",
     "lab": "Implement scaled dot-product attention from scratch",
     "hw": "Compute attention weights on a toy sequence",
     "viva": "What does Q, K, V represent? Multi-head attention?",
     "interview": "Explain attention mechanism. Why softmax?",
     "deliverable": "day53/day53_attention.ipynb", "revision": "Days 40-51",
     "mins_video": 90, "mins_lab": 90},

    {"day": 54, "module": "Deep Learning", "topic": "Transformer Architecture",
     "video": "Karpathy: Let's build GPT (first half)", "focus": "Encoder-decoder, positional encoding, layer norm",
     "lecture": "Transformer components",
     "math": "Positional encoding: PE(pos,2i) = sin(pos/10000^(2i/d))",
     "lab": "Build a mini-GPT character model (Karpathy code-along)",
     "hw": "Train on Shakespeare, generate text",
     "viva": "What is positional encoding? Why is it needed?",
     "interview": "Explain Transformer architecture end-to-end",
     "deliverable": "day54/day54_transformer.ipynb", "revision": "Day 53",
     "mins_video": 120, "mins_lab": 120},

    {"day": 55, "module": "Deep Learning", "topic": "HuggingFace Fundamentals",
     "video": "HuggingFace NLP Course Chapter 1-3", "focus": "Pipelines, tokenizers, models",
     "lecture": "The HuggingFace ecosystem",
     "math": "None",
     "lab": "Use 5 different pipelines: text-classification, NER, QA, summarization, generation",
     "hw": "Fine-tune BERT on a sentiment dataset",
     "viva": "How does AutoModel work? Tokenizer padding?",
     "interview": "How would you use HuggingFace for a production NLP task?",
     "deliverable": "day55/day55_huggingface.ipynb", "revision": "Day 54",
     "mins_video": 90, "mins_lab": 90},

    {"day": 56, "module": "Deep Learning", "topic": "Fine-Tuning Transformers",
     "video": "HuggingFace NLP Course Chapter 4-5", "focus": "Trainer API, custom training loop",
     "lecture": "Fine-tuning vs training from scratch",
     "math": "None",
     "lab": "Fine-tune DistilBERT on emotion classification",
     "hw": "Evaluate fine-tuned model vs zero-shot",
     "viva": "When to fine-tune vs prompt? LoRA?",
     "interview": "How would you fine-tune a model with limited compute?",
     "deliverable": "day56/day56_finetune.ipynb", "revision": "Day 55",
     "mins_video": 60, "mins_lab": 120},

    {"day": 57, "module": "Deep Learning", "topic": "WEEK 9 PROJECT: Text Classification with Transformers",
     "video": "None (project day)", "focus": "NLP production pipeline",
     "lecture": "None",
     "math": "None",
     "lab": "Build end-to-end sentiment analysis app: fine-tune DistilBERT + FastAPI endpoint + simple frontend",
     "hw": "Write model card on HuggingFace Hub",
     "viva": "Production considerations: latency, cost, drift",
     "interview": "How would you serve an NLP model in production?",
     "deliverable": "projects/week09_text_classifier/", "revision": "Days 53-56",
     "mins_video": 0, "mins_lab": 360, "is_project_day": True},

    # ══════════════════════════════════════════════════════════════════
    # MODULE 4: MLOps (Days 58-77)
    # ══════════════════════════════════════════════════════════════════

    {"day": 58, "module": "MLOps", "topic": "MLOps Overview",
     "video": "Andrew Ng MLOps Specialization Course 1 Week 1", "focus": "ML project lifecycle, data-centric AI",
     "lecture": "Research vs production ML",
     "math": "None",
     "lab": "Map out your Fraud Detection project against MLOps lifecycle",
     "hw": "Identify 3 production failure modes in your projects so far",
     "viva": "What makes a model production-ready?",
     "interview": "What is MLOps? How does it differ from DevOps?",
     "deliverable": "day58/day58_mlops_overview.ipynb", "revision": "Days 35-36",
     "mins_video": 60, "mins_lab": 60},

    {"day": 59, "module": "MLOps", "topic": "Experiment Tracking with MLflow",
     "video": "MLflow official tutorial", "focus": "Runs, experiments, model registry",
     "lecture": "None",
     "math": "None",
     "lab": "Add MLflow to your Fraud Detection project — log params, metrics, artifacts",
     "hw": "Compare 5 model experiments in MLflow UI",
     "viva": "Why experiment tracking matters in production",
     "interview": "How do you ensure reproducibility in ML experiments?",
     "deliverable": "day59/day59_mlflow.ipynb", "revision": "Day 58",
     "mins_video": 60, "mins_lab": 90},

    {"day": 60, "module": "MLOps", "topic": "Model Deployment with FastAPI",
     "video": "FastAPI official tutorial (quick)", "focus": "REST API for ML models",
     "lecture": "None",
     "math": "None",
     "lab": "Wrap your best ML model in FastAPI — POST /predict endpoint, Pydantic schema, joblib load",
     "hw": "Test with curl + write a simple Python client",
     "viva": "Synchronous vs async inference. Batching?",
     "interview": "How do you deploy an ML model as an API?",
     "deliverable": "day60/fraud_api/", "revision": "Day 35",
     "mins_video": 45, "mins_lab": 120},

    {"day": 61, "module": "MLOps", "topic": "Containerization — Docker for ML",
     "video": "Docker for ML tutorial", "focus": "Dockerfile, containers, images",
     "lecture": "Why containers in ML",
     "math": "None",
     "lab": "Dockerize your FastAPI + model — Dockerfile, docker-compose, test locally",
     "hw": "Build a multi-stage Dockerfile that minimizes image size",
     "viva": "Container vs VM. What is Docker layer caching?",
     "interview": "How do you containerize an ML model?",
     "deliverable": "day61/Dockerfile", "revision": "Day 60",
     "mins_video": 45, "mins_lab": 90},

    {"day": 62, "module": "MLOps", "topic": "Model Monitoring & Data Drift",
     "video": "Evidently AI tutorial + Andrew Ng MLOps Week 2", "focus": "Data drift, concept drift, monitoring",
     "lecture": "Production models degrade silently",
     "math": "KL divergence, PSI, Wasserstein distance",
     "lab": "Add Evidently monitoring to Fraud Detection — data drift report",
     "hw": "Simulate data drift — shift your test distribution, trigger an alert",
     "viva": "How do you detect model degradation?",
     "interview": "What is data drift? How do you monitor it in production?",
     "deliverable": "day62/day62_monitoring.ipynb", "revision": "Day 58",
     "mins_video": 60, "mins_lab": 90},

    {"day": 63, "module": "MLOps", "topic": "End-to-End MLOps Pipeline",
     "video": "None (synthesis day)", "focus": "Full production workflow",
     "lecture": "Connecting training → registry → serving → monitoring",
     "math": "None",
     "lab": "Connect: MLflow (tracking) → FastAPI (serving) → Evidently (monitoring) → simple alerting",
     "hw": "Document the full system design with architecture diagram",
     "viva": "Walk me through your full MLOps setup",
     "interview": "Design an ML system at scale",
     "deliverable": "day63/mlops_architecture.md", "revision": "Days 58-62",
     "mins_video": 0, "mins_lab": 180},

    {"day": 64, "module": "MLOps", "topic": "WEEK 10 PROJECT: Production ML System (Fraud Detection)",
     "video": "None (project day)", "focus": "Production-quality MLOps project",
     "lecture": "None",
     "math": "None",
     "lab": "Full production fraud detection: train → MLflow → FastAPI → Docker → monitoring → README → GitHub",
     "hw": "Deploy to Railway or Render free tier",
     "viva": "Full system review",
     "interview": "Walk me through your production ML system",
     "deliverable": "projects/week10_fraud_production/", "revision": "Days 58-63",
     "mins_video": 0, "mins_lab": 480, "is_project_day": True},

    # ══════════════════════════════════════════════════════════════════
    # MODULE 5: LLM, RAG & AI AGENTS (Days 65-98)
    # ══════════════════════════════════════════════════════════════════

    {"day": 65, "module": "LLM", "topic": "How LLMs Work",
     "video": "Karpathy: State of GPT + 3Blue1Brown Attention revisit", "focus": "Pretraining, RLHF, tokenization",
     "lecture": "From next-token prediction to ChatGPT",
     "math": "Perplexity: PP(W) = P(w1...wN)^(-1/N)",
     "lab": "Prompt engineering experiments — zero-shot, few-shot, CoT",
     "hw": "Write 10 prompts that fail and 10 that succeed for the same task",
     "viva": "Why do LLMs hallucinate?",
     "interview": "How are LLMs trained? RLHF?",
     "deliverable": "day65/day65_llm_fundamentals.ipynb", "revision": "Days 53-56",
     "mins_video": 90, "mins_lab": 60},

    {"day": 66, "module": "LLM", "topic": "Embeddings & Vector Search",
     "video": "HuggingFace Embeddings + FAISS tutorial", "focus": "Semantic embeddings, cosine similarity, ANN",
     "lecture": "How meaning becomes geometry",
     "math": "Cosine similarity, Euclidean vs inner product search",
     "lab": "Build a semantic search engine: embed 100 papers, query with cosine similarity",
     "hw": "Compare FAISS flat vs IVF index — speed vs accuracy tradeoff",
     "viva": "Why use vector search instead of keyword search?",
     "interview": "How does vector similarity search work at scale?",
     "deliverable": "day66/day66_embeddings.ipynb", "revision": "Days 5-6",
     "mins_video": 60, "mins_lab": 120},

    {"day": 67, "module": "LLM", "topic": "RAG Fundamentals",
     "video": "None + LangChain docs RAG quickstart", "focus": "Retrieval-Augmented Generation pipeline",
     "lecture": "Why RAG beats fine-tuning for knowledge",
     "math": "None",
     "lab": "Build RAG from scratch: chunk → embed → store in FAISS → retrieve → prompt → generate",
     "hw": "RAG on your own PDF notes — ask questions",
     "viva": "When does RAG fail? Hallucination in RAG?",
     "interview": "Design a RAG system. How would you evaluate it?",
     "deliverable": "day67/day67_rag_scratch.ipynb", "revision": "Day 66",
     "mins_video": 60, "mins_lab": 150},

    {"day": 68, "module": "LLM", "topic": "LangChain Fundamentals",
     "video": "LangChain official tutorial", "focus": "Chains, prompts, memory, retrievers",
     "lecture": "LangChain as LLM orchestration",
     "math": "None",
     "lab": "Rebuild yesterday's RAG using LangChain — compare code complexity",
     "hw": "Add conversation memory to your RAG",
     "viva": "LangChain vs raw API calls — tradeoffs?",
     "interview": "What is LangChain? When would you not use it?",
     "deliverable": "day68/day68_langchain.ipynb", "revision": "Day 67",
     "mins_video": 90, "mins_lab": 90},

    {"day": 69, "module": "LLM", "topic": "ChromaDB & Production Vector Stores",
     "video": "ChromaDB docs + comparison tutorial", "focus": "Persistent storage, metadata filtering",
     "lecture": "FAISS vs Chroma vs Pinecone tradeoffs",
     "math": "None",
     "lab": "Migrate your FAISS RAG to ChromaDB — add metadata filters",
     "hw": "Benchmark: query time FAISS vs Chroma on 10K documents",
     "viva": "When to use a vector database vs in-memory FAISS?",
     "interview": "How do you choose a vector store for production?",
     "deliverable": "day69/day69_chromadb.ipynb", "revision": "Day 67",
     "mins_video": 60, "mins_lab": 90},

    {"day": 70, "module": "LLM", "topic": "Advanced RAG Patterns",
     "video": "RAG survey paper + LangChain advanced RAG", "focus": "HyDE, re-ranking, parent-child chunking",
     "lecture": "Why naive RAG fails",
     "math": "None",
     "lab": "Add re-ranking to your RAG — use a cross-encoder for re-scoring",
     "hw": "Evaluate naive RAG vs advanced RAG using RAGAS",
     "viva": "Why does chunking strategy matter?",
     "interview": "How would you improve a RAG system that gives poor answers?",
     "deliverable": "day70/day70_advanced_rag.ipynb", "revision": "Days 67-69",
     "mins_video": 60, "mins_lab": 120},

    {"day": 71, "module": "LLM", "topic": "WEEK 11 PROJECT: Document QA System",
     "video": "None (project day)", "focus": "Production RAG system",
     "lecture": "None",
     "math": "None",
     "lab": "Build: multi-document RAG + ChromaDB + LangChain + FastAPI + simple chat UI + RAGAS evaluation",
     "hw": "Deploy on Railway free tier",
     "viva": "Full system review",
     "interview": "Walk through your RAG system architecture",
     "deliverable": "projects/week11_document_qa/", "revision": "Days 65-70",
     "mins_video": 0, "mins_lab": 480, "is_project_day": True},

    {"day": 72, "module": "LLM", "topic": "AI Agents & Tool Use",
     "video": "LangChain Agents tutorial + Karpathy AgentGPT video", "focus": "ReAct, tool calling, planning",
     "lecture": "Agents vs chains — when to use each",
     "math": "None",
     "lab": "Build a ReAct agent with 3 tools: calculator, web search, code runner",
     "hw": "Test your agent on 10 tasks — where does it fail?",
     "viva": "What is the AgentExecutor loop?",
     "interview": "Design an AI agent for [X task]",
     "deliverable": "day72/day72_agents.ipynb", "revision": "Day 68",
     "mins_video": 90, "mins_lab": 120},

    {"day": 73, "module": "LLM", "topic": "LangGraph — Stateful Multi-Agent Systems",
     "video": "LangGraph official tutorial", "focus": "Nodes, edges, state, conditional routing",
     "lecture": "When single-agent ReAct is not enough",
     "math": "None",
     "lab": "Build a 2-agent system: Researcher + Writer with shared state",
     "hw": "Add a supervisor/orchestrator agent",
     "viva": "LangGraph vs LangChain Agents — key differences?",
     "interview": "Multi-agent architectures — when and why?",
     "deliverable": "day73/day73_langgraph.ipynb", "revision": "Day 72",
     "mins_video": 90, "mins_lab": 120},

    {"day": 74, "module": "LLM", "topic": "LLM Evaluation",
     "video": "RAGAS paper walkthrough", "focus": "Faithfulness, answer relevancy, context recall",
     "lecture": "Evaluating what humans can't manually check",
     "math": "Faithfulness score formula",
     "lab": "Evaluate your Document QA system with RAGAS — get a baseline",
     "hw": "Improve one RAGAS metric by 10%",
     "viva": "How do you evaluate an LLM application?",
     "interview": "LLM evaluation strategies in production",
     "deliverable": "day74/day74_evaluation.ipynb", "revision": "Days 67-71",
     "mins_video": 45, "mins_lab": 90},

    {"day": 75, "module": "LLM", "topic": "WEEK 12 PROJECT: Multi-Agent Financial Analyst",
     "video": "None (project day)", "focus": "Complex multi-agent system",
     "lecture": "None",
     "math": "None",
     "lab": "Build: Agent 1 (document ingestion + RAG) + Agent 2 (data extraction) + Agent 3 (report generation) using LangGraph + ChromaDB + FastAPI",
     "hw": "RAGAS evaluation + architecture diagram",
     "viva": "Full system review",
     "interview": "Design your most complex AI system",
     "deliverable": "projects/week12_financial_analyst/", "revision": "Days 65-74",
     "mins_video": 0, "mins_lab": 480, "is_project_day": True},

    # ══════════════════════════════════════════════════════════════════
    # MODULE 6: CAPSTONE & PORTFOLIO (Days 76-112)
    # ══════════════════════════════════════════════════════════════════

    {"day": 76, "module": "Capstone", "topic": "ML System Design",
     "video": "ML System Design (Chip Huyen — selected chapters)", "focus": "Feature stores, online/offline learning, latency",
     "lecture": "None",
     "math": "None",
     "lab": "Design on paper: a recommendation system at 1M users",
     "hw": "Read Chip Huyen Chapter 1-3",
     "viva": "Design a fraud detection system at Netflix scale",
     "interview": "ML System Design interview preparation",
     "deliverable": "interview-notes/system_design.md", "revision": "Days 35, 64",
     "mins_video": 60, "mins_lab": 90},

    {"day": 77, "module": "Capstone", "topic": "Interview Preparation — Classical ML",
     "video": "None (interview prep day)", "focus": "Full ML interview circuit",
     "lecture": "None",
     "math": "Re-derive key formulas",
     "lab": "Recode: Linear Regression + Logistic Regression + Decision Tree from scratch in 90 minutes",
     "hw": "50 ML interview questions — write answers",
     "viva": "Mock ML interview",
     "interview": "Full classical ML interview simulation",
     "deliverable": "interview-notes/classical_ml_qa.md", "revision": "Days 12-35",
     "mins_video": 0, "mins_lab": 180, "is_revision_day": True},

    {"day": 78, "module": "Capstone", "topic": "Interview Preparation — Deep Learning",
     "video": "None (interview prep day)", "focus": "DL interview circuit",
     "lecture": "None",
     "math": "Backprop, attention, CNN formulas",
     "lab": "Recode: Neural Network from scratch + attention mechanism in 90 minutes",
     "hw": "50 DL interview questions",
     "viva": "Mock DL interview",
     "interview": "Full DL interview simulation",
     "deliverable": "interview-notes/deep_learning_qa.md", "revision": "Days 40-57",
     "mins_video": 0, "mins_lab": 180, "is_revision_day": True},

    {"day": 79, "module": "Capstone", "topic": "Interview Preparation — LLM & Agents",
     "video": "None (interview prep day)", "focus": "LLM/RAG/Agents interview circuit",
     "lecture": "None",
     "math": "Attention formula, RAG pipeline",
     "lab": "Build a mini-RAG in 60 minutes from memory",
     "hw": "50 LLM interview questions",
     "viva": "Mock LLM interview",
     "interview": "Full LLM/Agent interview simulation",
     "deliverable": "interview-notes/llm_qa.md", "revision": "Days 65-75",
     "mins_video": 0, "mins_lab": 180, "is_revision_day": True},

    {"day": 80, "module": "Capstone", "topic": "CAPSTONE: Production AI System — Architecture",
     "video": "None", "focus": "System design",
     "lecture": "None",
     "math": "None",
     "lab": "Design the full capstone system — architecture diagram, tech stack, data flow",
     "hw": "Write technical spec document",
     "viva": "Architecture review",
     "interview": "Explain your capstone project",
     "deliverable": "capstone/ARCHITECTURE.md", "revision": "All modules",
     "mins_video": 0, "mins_lab": 240},

    {"day": 81, "module": "Capstone", "topic": "CAPSTONE: Backend & ML Core",
     "video": "None", "focus": "Core implementation",
     "lecture": "None",
     "math": "None",
     "lab": "Build: FastAPI backend + ML pipeline + database integration",
     "hw": "Write tests for core functions",
     "viva": "Code review",
     "interview": "Walk through your backend architecture",
     "deliverable": "capstone/backend/", "revision": "Days 60-64",
     "mins_video": 0, "mins_lab": 300},

    {"day": 82, "module": "Capstone", "topic": "CAPSTONE: LLM & RAG Integration",
     "video": "None", "focus": "LLM integration",
     "lecture": "None",
     "math": "None",
     "lab": "Integrate LangGraph agents + RAG + vector store into backend",
     "hw": "RAGAS evaluation baseline",
     "viva": "Agent design review",
     "interview": "Walk through your LLM integration",
     "deliverable": "capstone/llm_pipeline/", "revision": "Days 67-75",
     "mins_video": 0, "mins_lab": 300},

    {"day": 83, "module": "Capstone", "topic": "CAPSTONE: Frontend & UI",
     "video": "None", "focus": "Frontend",
     "lecture": "None",
     "math": "None",
     "lab": "Build React or Streamlit UI for the capstone system",
     "hw": "User testing — give to 3 people, collect feedback",
     "viva": "UX review",
     "interview": "Walk through user experience",
     "deliverable": "capstone/frontend/", "revision": "None",
     "mins_video": 0, "mins_lab": 300},

    {"day": 84, "module": "Capstone", "topic": "CAPSTONE: Testing, Evaluation & Documentation",
     "video": "None", "focus": "Quality + documentation",
     "lecture": "None",
     "math": "None",
     "lab": "Write tests, evaluation suite, README, model card, architecture doc",
     "hw": "Peer code review",
     "viva": "Full project review",
     "interview": "Walk through your testing strategy",
     "deliverable": "capstone/tests/ + capstone/README.md", "revision": "None",
     "mins_video": 0, "mins_lab": 240},

    {"day": 85, "module": "Capstone", "topic": "CAPSTONE: Deployment",
     "video": "None", "focus": "Production deployment",
     "lecture": "None",
     "math": "None",
     "lab": "Dockerize + deploy to Railway/Fly.io + CI/CD + monitoring",
     "hw": "Load test + cost analysis",
     "viva": "Production readiness review",
     "interview": "Walk through your deployment",
     "deliverable": "capstone/Dockerfile + deploy URL", "revision": "Days 61-64",
     "mins_video": 0, "mins_lab": 300},

    # FINAL REVISION & PORTFOLIO (Days 86-112)
]

# Fill remaining days 86-112 with revision, mock interviews, portfolio polish
REVISION_TOPICS = [
    ("Portfolio: GitHub README Polish", "Review every repo, add demos, fix READMEs"),
    ("Mock Interview 1: Classical ML", "Full 45-min mock ML interview, record yourself"),
    ("Mock Interview 2: Deep Learning", "Full 45-min mock DL interview"),
    ("Mock Interview 3: ML System Design", "Full 45-min system design interview"),
    ("Mock Interview 4: LLM & RAG", "Full LLM/RAG interview simulation"),
    ("Weak Areas Revision", "Identify weakest 3 topics, revise and recode"),
    ("Statistics & Math Revision", "Rederive key formulas without notes"),
    ("LeetCode Medium Burst", "5 LeetCode mediums: arrays, trees, DP, graphs"),
    ("End-to-End Project Review", "Run all 5 projects end-to-end, fix anything broken"),
    ("LinkedIn & Resume Update", "Update with all projects, skills, and certifications"),
    ("GitHub Activity Finalization", "Ensure 100+ commits, clean repos, write READMEs"),
    ("Mock Interview 5: Full Loop Simulation", "Complete 6-round mock interview, timed"),
    ("Coding: Advanced NumPy & ML from scratch", "Recode 3 algorithms in 60 minutes without notes"),
    ("LLM Interview Deep Dive", "Attention, RAG, agents — 20 advanced questions"),
    ("Capstone Demo Preparation", "Prepare 10-minute live demo walkthrough"),
    ("MLOps & Deployment Review", "Docker, FastAPI, monitoring — walk through setup"),
    ("Behavioral Interview Preparation", "STAR format for 10 key stories"),
    ("Final Math Review: Linear Algebra + Calculus", "Vectors, matrices, derivatives, chain rule"),
    ("Final Algorithms Review: Trees, Graphs, DP", "5 problems from each category"),
    ("Capstone: Final Polish", "Fix last bugs, finalize documentation, record demo"),
    ("GitHub Portfolio Final Review", "Pin best 6 repos, write a portfolio README"),
    ("Mock Interview 6: Company-Specific Prep", "Prepare for target company coding + ML round"),
    ("Open Source Contribution", "Find a beginner-friendly issue, submit a PR"),
    ("Blog Article: My 112-Day Journey", "Write a LinkedIn post about what you built"),
    ("Day 110: Final Revision Sprint", "Rapid-fire Q&A on all 5 modules"),
    ("Day 111: Rest & Reflection", "No coding. Reflect on progress. Plan job applications."),
    ("Day 112: GRADUATION — Production ML Engineer", "Portfolio complete. Interview ready. Apply."),
]

REVISION_DAYS = []
for idx, (topic, focus) in enumerate(REVISION_TOPICS):
    day_num = 86 + idx
    if day_num > 112:
        break
    REVISION_DAYS.append({
        "day": day_num,
        "module": "Capstone",
        "topic": topic,
        "video": "None",
        "focus": focus,
        "lecture": "None",
        "math": "None",
        "lab": focus,
        "hw": "None",
        "viva": "Mock viva",
        "interview": focus,
        "deliverable": f"revision/day{day_num:03d}.md",
        "revision": "All",
        "mins_video": 0,
        "mins_lab": 180,
        "is_revision_day": True,
    })

CURRICULUM.extend(REVISION_DAYS)


def get_curriculum():
    return CURRICULUM


def get_day(n):
    """Get curriculum for Day N."""
    return next((c for c in CURRICULUM if c["day"] == n), None)
